### ISSUE TITLE
Day 3 - part 8

### ISSUE THREAD

**Issue by palli710** [hgop/syllabus-2020#14]
I'm unable to complete the last part of step 8, I always get 'unable to connect..', even though I have already edited the csr.conf.template file. Been stuck on this since yesterday. 
I can run the command if I include "--insecure-skip-tls-verify", but I'm guessing that's a bad work-around the issue. 

![hmm](https://user-images.githubusercontent.com/42967141/100345103-bd950200-2fd9-11eb-8259-d3b4486b9f93.jpg)

**Comment by Fanneyyy** [comment]
We need a bit more information:
1. If you cat `/var/snap/microk8s/current/certs/csr.conf.template` from your MicroK8s instance, does it include `DNS.6 = pair4.hgopteam.com`.
2. If you cat your local ./kube/config does in include:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: …
    server: https://pair4.hgopteam.com:16443 <- This line
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: …
```
