### ISSUE TITLE
Villu í pipeline-inu

### ISSUE THREAD

**Issue by soleyhr** [hgop/syllabus-2020#47]
Við fáum þessa villu í pipeline-inu eftir að gerðum part 2 í degi 12.
Þannig það runnar ekki án failure ☹️ 
Ef við gerum npx cypress cache path þá fáum við /Users/soleybirgisdottir/Library/Caches/Cypress eins og það sé að lenda á vitlausum stað :S
Hvernig lögum við það?

<img width="915" alt="Screen Shot 2020-12-09 at 00 34 24" src="https://user-images.githubusercontent.com/34030123/101558362-b5b06700-39b6-11eb-82d6-62bc545f628d.png">

**Comment by Fanneyyy** [comment]
This can be solved with changing:
```
  e2e-test:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run: cd e2e && npm install && npm test
```
to:
```
  e2e-test:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run: cd e2e
      - run: npm install
      - run: npm test
```
